name: Backend CI

on:
    push:
        branches: [master]
    pull_request:

jobs:
    setup:
        if: contains(github.event.pull_request.labels.*.name, 'backend')
        runs-on: ubuntu-latest
        defaults:
            run:
                working-directory: ./backend

        steps:
            - uses: actions/checkout@v3
            - name: Set up Python
              uses: actions/setup-python@v4
              with:
                  python-version: 3.11

            - name: Install poetry
              run: |
                  curl -sSL "https://install.python-poetry.org" | python
                  echo "$HOME/.poetry/bin" >> $GITHUB_PATH

            - name: Install dependencies
              run: |
                  poetry config virtualenvs.in-project true
                  poetry run pip install -U pip
                  poetry install

    lint:
        runs-on: ubuntu-latest
        needs: setup
        defaults:
            run:
                working-directory: backend

        steps:
            - uses: actions/checkout@v3
            - name: Run Mypy
              run: poetry run mypy app

            - name: Run Flake8
              run: poetry run flake8 app

    test:
        runs-on: ubuntu-latest
        needs: setup
        defaults:
            run:
                working-directory: backend

        steps:
            - uses: actions/checkout@v3
            - name: Run tests
              run: poetry run pytest tests
